import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import dynamic from 'next/dynamic';
import Link from 'next/link';
import Panel from '../components/shared/Panel';
import { getSession } from 'next-auth/react';
import Header from '../components/shared/Header';
const CreatePropertyForm = dynamic(() => import('../components/CreatePropertyForm'), {
  ssr: false,
});

const CreateProperty: NextPage = () => {
  return (
    <>
      <Header title={"snowcap"} />
      <div className={styles.container}>
        <Head>
          <title>Snowcap - create</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <Panel title={"create"}>
            <CreatePropertyForm />
          </Panel>
        </main>
      </div>
    </>
  )
}

export default CreateProperty;

export async function getServerSideProps(context: any) {
  const session = await getSession(context) as any

  if (!session) {
    return {
      redirect: {
        destination: '/sign-in',
        permanent: false,
      },
    }
  }
  return {
    props: { session }
  }
}