import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Panel from '../components/shared/Panel'
import Link from 'next/link'
import LandingBox from '../components/LandingBox'
import { getSession } from 'next-auth/react'
import Header from '../components/shared/Header'

const Home: NextPage = () => {
  return (
    <>
      <Header title={"snowcap"} />
      <div className={styles.container}>
        <Head>
          <title>Snowcap</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <Panel title={"home"}>
            <LandingBox />
          </Panel>
        </main>
      </div>
    </> 
  )
}

export default Home;

export async function getServerSideProps(context: any) {
  const session = await getSession(context) as any

  if (!session) {
    return {
      redirect: {
        destination: '/sign-in',
        permanent: false,
      },
    }
  }
  return {
    props: { session }
  }
}