import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Panel from '../components/shared/Panel'
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Snowcap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Panel title={"home"}>
          <h1 className={styles.title}>
            welcome to <a>snowcap</a>!
          </h1>

          <p className={styles.description}>
            Get started by {' '}
            <Link href='/create'>creating a property</Link>!
          </p>

          <p className={styles.description}>
            You can also view created {' '}
            <Link href='/properties'>properties</Link>{'.'}
          </p>
        </Panel>
      </main>
    </div>
  )
}

export default Home
