

import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import dynamic from 'next/dynamic';
import Link from 'next/link';
import Panel from '../components/shared/Panel';
import PropertyList from '../components/properties/PropertyList';
const Log = dynamic(() => import('../components/Log'), {
  ssr: false,
});

const LogPage: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>snowcap - Properties</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Panel title={"properties"}>
          {/* <Log /> */}
          <PropertyList />
        </Panel>
      </main>
    </div>
  )
}

export default LogPage