

import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Panel from '../components/shared/Panel';
import PropertyList from '../components/properties/PropertyList';
import { getSession } from 'next-auth/react';
import Header from '../components/shared/Header';

const LogPage: NextPage = () => {
  return (
    <>
    <Header title={"snowcap"} />
    <div className={styles.container}>
      <Head>
        <title>snowcap - Properties</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Panel title={"properties"}>
          {/* <Log /> */}
          <PropertyList />
        </Panel>
      </main>
    </div>
    </>
  )
}

export default LogPage;

export async function getServerSideProps(context: any) {
  const session = await getSession(context) as any

  if (!session) {
    return {
      redirect: {
        destination: '/sign-in',
        permanent: false,
      },
    }
  }
  return {
    props: { session }
  }
}