import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import dynamic from 'next/dynamic';
import Link from 'next/link';
import Panel from '../components/shared/Panel';
const ScribeForm = dynamic(() => import('../components/ScribeForm'), {
  ssr: false,
});

const Upload: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Snowcap - upload</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Panel title={"record or upload"}>
          <ScribeForm />
        </Panel>
      </main>
    </div>
  )
}

export default Upload