import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import dynamic from 'next/dynamic';
import Panel from '../components/shared/Panel';
import { getSession } from 'next-auth/react';
import Header from '../components/shared/Header';
const ScribeForm = dynamic(() => import('../components/ScribeForm'), {
  ssr: false,
});

const Upload: NextPage = () => {
  return (
    <>
      <Head>
        <title>snowcap - Record</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header title={"snowcap"} />
      <div className={styles.container}>
        <main className={styles.main}>
          <Panel title={"record or upload"}>
            <ScribeForm />
          </Panel>
        </main>
      </div>
    </>
  )
}

export default Upload;

export async function getServerSideProps(context: any) {
  const session = await getSession(context) as any

  if (!session) {
    return {
      redirect: {
        destination: '/sign-in',
        permanent: false,
      },
    }
  }
  return {
    props: { session }
  }
}