import { Box } from "@chakra-ui/react";
import SignInForm from "../components/auth/SignInForm";
import Header from "../components/shared/Header";
import Head from "next/head";
import Panel from "../components/shared/Panel";

const SignInPage = () => {
  return (
    <>
      <Head>
        <title>snowcap - Sign In</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header title={"snowcap"} noNav />
      <Panel title={"sign in"}>
          <SignInForm />
      </Panel>
    </>
  );
};

export default SignInPage;